# Generated by Django 4.2.29 on 2026-03-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_remove_skill_image_url_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years_of_experience',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
