# Generated by Django 4.2.29 on 2026-03-12 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('skill', '0003_alter_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.image')),
                ('image', models.ImageField(upload_to='skill/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('base.image',),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skill.skillimage'),
        ),
    ]
