# Generated by Django 4.2.29 on 2026-03-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_skillimage_remove_skill_image_skill_skill_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='skillimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='skillimage',
            name='order',
        ),
    ]
