# Generated by Django 4.2.29 on 2026-03-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('education', '0003_education_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.image')),
                ('image', models.ImageField(upload_to='education/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='education.education')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.image',),
        ),
    ]
