# Generated by Django 4.2.29 on 2026-03-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_achievement_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='certificate_url',
        ),
        migrations.DeleteModel(
            name='AchievementImage',
        ),
    ]
