# Generated by Django 4.2.29 on 2026-03-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_achievement_certificate_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationimage',
            name='caption',
        ),
    ]
