# Generated by Django 4.2.29 on 2026-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_educationimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationimage',
            name='path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
