# Generated by Django 4.2.29 on 2026-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_educationimage_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationimage',
            name='path',
        ),
        migrations.AddField(
            model_name='education',
            name='image_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
