# Generated by Django 4.2.29 on 2026-03-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_remove_educationimage_path_education_image_paths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='image_paths',
        ),
    ]
