"""
Django settings for portfolio_be project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s1$@j+rx+=&)3xzh%s$wjo00rbhx(uj0www5o^8cf88nv%#x-#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['*']  # Allow all hosts (for development only)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'django_extensions',
    'drf_spectacular',
    'base',
    'auth_user',
    'expense',
    'todo',
    'skill',
    'album',
    'education',
    'notepad',
    'tracking',
    'blog',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'portfolio_be.middleware.APIResponseWrapperMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'portfolio_be.middleware.FrameOptionsOverrideMiddleware',  # Override X-Frame-Options for PDF preview
]

ROOT_URLCONF = 'portfolio_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_be.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME','portfolio_be'),    # Your database name
        'USER': os.getenv('DB_USER','postgres'),        # Your database username
        'PASSWORD': os.getenv('DB_PASSWORD','password'), # Your database password
        'HOST': os.getenv('DB_HOST', 'localhost'),     # Database host (e.g., 'localhost' or an IP address)
        'PORT': os.getenv('DB_PORT', '5432'),          # Database port (default for Postgres)
        'CONN_MAX_AGE': 0,  # Disable persistent connections
        'OPTIONS': {
            'sslmode': 'disable',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Allow iframe embedding (for PDF preview from frontend)
# In development, allow all origins; in production, use 'SAMEORIGIN'
if DEBUG:
    X_FRAME_OPTIONS = '*'          # Development: allow all
else:
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Production: same origin only

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ── drf-spectacular (OpenAPI 3 / Swagger) ────────────────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE': 'Portfolio Backend API',
    'DESCRIPTION': 'REST API for the Portfolio project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,  # Swagger UI needs this to render properly
}


# Basic logging so middleware debug messages appear during development
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'portfolio_be.middleware': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
CORS_ALLOW_ALL_ORIGINS = True
# CORS (Cross-Origin Resource Sharing) settings for local development
# Allow the frontend dev server (Vite) to talk to this API.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://.*$",
]
# If you want a quick dev hack, you can set CORS_ALLOW_ALL_ORIGINS = True
# but prefer explicit origins above for safety.
CORS_ALLOW_CREDENTIALS = True
