# Generated by Django 4.2.29 on 2026-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
