# Generated by Django 4.2.29 on 2026-03-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_albumimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='caption',
        ),
    ]
