# Generated by Django 4.2.29 on 2026-03-12 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tracking_visitor',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('path', models.CharField(max_length=2048)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referrer', models.CharField(blank=True, max_length=2048)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consent', models.BooleanField(db_index=True, default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageviews', to='tracking.visitor')),
            ],
            options={
                'db_table': 'tracking_pageview',
                'indexes': [models.Index(fields=['ip_hash'], name='tracking_pa_ip_hash_41760c_idx'), models.Index(fields=['timestamp'], name='tracking_pa_timesta_6e8129_idx'), models.Index(fields=['consent'], name='tracking_pa_consent_81925c_idx')],
            },
        ),
    ]
