# Generated by Django 4.2.19 on 2026-03-08 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=200)),
                ('strokes', models.JSONField(blank=True, default=list)),
                ('canvas_width', models.PositiveIntegerField(default=800)),
                ('canvas_height', models.PositiveIntegerField(default=400)),
                ('device_pixel_ratio', models.FloatField(default=1.0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='notepad/thumbnails/')),
            ],
            options={
                'verbose_name': 'Drawing',
                'verbose_name_plural': 'Drawings',
                'ordering': ['-created_at'],
            },
        ),
    ]
